### ISSUE TITLE
Typo in default focal length 

### ISSUE THREAD

**Issue by GrumpyZhou** [ActiveVisionLab/direct-posenet#2]
Hi I found the default value of  focal length you set is  558 but it should be 585:

https://github.com/ActiveVisionLab/direct-posenet/blob/43854703b1cfc5a65e39ceb8899cd41dd3f7ad09/dataset_loaders/seven_scenes.py#L153-L157

**Comment by chenusc11** [comment]
Hi, @GrumpyZhou many thanks for raising this issue. I did try both focal 558 and 585 and found they make very little difference on my model. I chose 558 from my re-alignment using COLMAP. 

Did you find any difference between these two focal? If so, I will change this.

**Comment by GrumpyZhou** [comment]
I didn't run anything with your code.  I was just looking at it and found inconsistency. Basically in another place you are using 585: 

https://github.com/ActiveVisionLab/direct-posenet/blob/43854703b1cfc5a65e39ceb8899cd41dd3f7ad09/dataset_loaders/load_7Scenes.py#L50-L54

Therefore I thought it might be some typos.

**Comment by chenusc11** [comment]
I see. Thanks. After checking with my current implementation, I can confirm that 585 is correct. Therefore I updated a fix.

Will close the issue for now
