### ISSUE TITLE
Question about how to calculate pose_avg_stats.txt?

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/direct-posenet#3]
Hi, 

Thanks for your excellent work. May I know did you refer it to compute averaged poses of [R,t]? https://github.com/kwea123/nerf_pl/blob/52aeb387da64a9ad9a0f914ea9b049ffc598b20c/datasets/llff.py#L17 

Hope for your reply!

**Comment by chenusc11** [comment]
Hi, yes. I pre-stored the pose_avg_stats.txt with the --save_pose_avg_stats flag.

**Comment by LZL-CS** [comment]
> Hi, yes. I pre-stored the pose_avg_stats.txt with the --save_pose_avg_stats flag.

ok, thanks for your reply. I will close the issue now.
