### ISSUE TITLE
Question about rotation matrix to quaternion using pytorch3d

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/direct-posenet#5]
Hi,
When I tried to use pytorch3d to calculate quaternion, I found the result was quite different from those calculated by TensorFlow packages. 

> e.g: poses=[0.85091,-0.09300,0.51649,-0.15116
                       0.12269,0.99195,-0.02347,0.01480
                       -0.51026,0.08340,0.85567,-0.05507]

`pose_q = tfg_transformation.quaternion.from_rotation_matrix(pose[:, :3, :3])`:
the result is: `tf.Tensor([[0.02778392 0.26694304 0.05607757 0.9615785 ]], shape=(1, 4), dtype=float32)`

`pytorch3d.transforms.matrix_to_quaternion(torch.tensor(pose[:, :3, :3]))`:
the result is: `tensor([[0.9616, 0.0287, 0.2671, 0.0566]])`

May I know whether you have any idea about the wired result? Thanks in advance!

**Comment by chenusc11** [comment]
Yeah I found the similar issue before. 

When I was developing this project, pytorch3d was a relatively new package. In this project, I was mainly using the tensorflow_graphics.geometry.transformation package to train and test. 

The precision between both packages were different so I would suggest that to use the same package for training and testing.

**Comment by LZL-CS** [comment]
Thanks for your reply, I will keep the same with your setting in the code.
