### ISSUE TITLE
Question about colmap-based coordinate

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/direct-posenet#6]
Hi, when I run the colmap to get the image poses, and then I plot it to compare it with 7Scenes-poses (heads scene), the result is quite different from yours. Do you know what's the problem of it or could you share your code about how to process generated colmap poses of images? Thank you in advance!

1. Colmap sparse reconstruction result:
 

![colmap_model](https://user-images.githubusercontent.com/54640259/195059974-7fcf78b6-dad5-412e-8e4c-14797cdb2d69.png)

2. Plot coordinates of 7Scenes-pose and colmap-pose (the blue is 7Scenes and the orange is generated by colmap):
![coordinates_comparision](https://user-images.githubusercontent.com/54640259/195061006-587a2fa1-376b-414d-87fd-01bf279a6321.png)

**Comment by chenusc11** [comment]
Hi, I'm not sure what happened. This doesn't look right.

I used this [code](https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py)

Should be something looking like this I think...

![Screen Shot 2022-10-11 at 2 22 01 PM](https://user-images.githubusercontent.com/8814381/195102444-87c182c0-3f85-4559-ab86-3e3c8718d51b.png)

**Comment by LZL-CS** [comment]
Hi @chenusc11, thanks for your quick reply. Whether you also use **colmap GUI** to sparsely construct the head scene and then use [code](https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py) to get organized poses? If so, I guess the reason is that you take part in training/validation images while I use all training/validation images, thus the trajectory is quite different!

**Comment by chenusc11** [comment]
This is the full train+val images files I ran from COLMAP (see 0.zip below). Please check if you can get the same results as mine. I use the code provided earlier, and only feed the output files to GUI for visualization.

[0.zip](https://github.com/ActiveVisionLab/direct-posenet/files/9757575/0.zip)


![Screen Shot 2022-10-11 at 4 33 58 PM](https://user-images.githubusercontent.com/8814381/195135579-d06908ba-5ea2-4f38-a7c1-33cdade1c03a.png)

**Comment by LZL-CS** [comment]
ok, I will check it, thank you very much!

**Comment by LZL-CS** [comment]
> This is the full train+val images files I ran from COLMAP (see 0.zip below). Please check if you can get the same results as mine. I use the code provided earlier, and only feed the output files to GUI for visualization.
> 
> [0.zip](https://github.com/ActiveVisionLab/direct-posenet/files/9757575/0.zip)
> 
> ![Screen Shot 2022-10-11 at 4 33 58 PM](https://user-images.githubusercontent.com/8814381/195135579-d06908ba-5ea2-4f38-a7c1-33cdade1c03a.png)

Hi @chenusc11, I re-run the colmap and then plot the trajectory, the result is the same as yours, thanks for your help!

**Comment by LZL-CS** [comment]
Hi @chenusc11, I re-run the colmap and got the same result as yours (the data is [zip](https://drive.google.com/file/d/1lU2v85ynnXEkzdxs0NvTRQJAHdpjWJtl/view?usp=sharing) ):
![1](https://user-images.githubusercontent.com/54640259/195490200-38a8ed29-bad6-47c5-a99c-d08c2b5bc4a1.png)

However, when I plot the [poses_bounds.npy](https://drive.google.com/file/d/1kD6JwGFq1geu7Y8_0NlXi3x-yqBg_8jq/view?usp=sharing)  of colmap (processed by [LLFF](https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py)) and 7Scenes poses  (train +val of heads), the result is still different from yours. It  seems that the **xyz-value scale** is different between colmap and 7Scenes:
![2](https://user-images.githubusercontent.com/54640259/195493676-61fa0ab0-9d54-421c-bd95-d76f805921a5.png)

My code for visualization is [here](https://drive.google.com/file/d/1vvFk69aJ4HuaLEklJHsFXKlpCkcQNXBk/view?usp=sharing).

**Comment by chenusc11** [comment]
Hi, this is as expected since COLMAP doesn't predict real-world scale and intrinsic of the scene. 

You can rescale the COLMAP pose with a factor of X to visualize it in a similar scale with our GT poses provided by the dataset.

**Comment by LZL-CS** [comment]
> Hi, this is as expected since COLMAP doesn't predict real-world scale and intrinsic of the scene.
> 
> You can rescale the COLMAP pose with a factor of X to visualize it in a similar scale with our GT poses provided by the dataset.

Hi @chenusc11, got it and thanks for your reply, I will close this issue.
