### ISSUE TITLE
question about colmap data processing

### ISSUE THREAD

**Issue by LZL-CS** [ActiveVisionLab/direct-posenet#7]
Hi, I am a little bit confused about whether you use the **part** or  **full** code from [imgs2poses](https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py) to process your clomap data.

> 1. part code of imgs2poses:
> <img width="898" alt="image" src="https://user-images.githubusercontent.com/54640259/197399235-70ac1659-a508-4553-8b79-9d87647bde04.png">

> 2. full code of imgs2poses:
> <img width="910" alt="image" src="https://user-images.githubusercontent.com/54640259/197399374-2950e8d2-4541-4809-b2d9-c11c2fec72c6.png">

Because from visualized results, the xyz-trajectory is the same in both ways, may I know which one you used?

**Comment by chenusc11** [comment]
Hi, sorry I did not quite understand the question. I didn't change anything in img2poses so I guess I'm using the full script.

**Comment by LZL-CS** [comment]
> Hi, sorry I did not quite understand the question. I didn't change anything in img2poses so I guess I'm using the full script.

Hi @chenusc11 , got it, and thanks for your reply.
