### ISSUE TITLE
perturb_rotation usage?

### ISSUE THREAD

**Issue by cazhang** [ActiveVisionLab/direct-posenet#8]
Hello, I found the function of perturb_rotation in load_7Scenes, my intent usage of this is to perturb the camera rotation by some degrees. Using c2w (3x4) matrix as input, however, I found that the last column (eg. camera position) also gets changed. 
I didn't find the usage of this function in your codebase, could you let me know how do you apply this in your project?

I'm following your preprocessing of sevenscenes, first fixing the rotation matrix order, and then doing the perturbation. 

Thanks,
Chao

**Comment by chenusc11** [comment]
I think I did the same. You can rotate the 3x3 matrix and apply back the original translation pose to your 3x4.

**Comment by cazhang** [comment]
I think holding translations before and after rotation perturbed makes sense. I solved this by using scipy Rotation to decompose R to Euler angles first(xyz order corresponding to right/up/back), and then update angles, finally converting back to matrix. This only uses 3x3 rotation matrices. 

Thanks for the reply. I'm now closing this.
