### ISSUE TITLE
Torch ngp training

### ISSUE THREAD

**Issue by cazhang** [ActiveVisionLab/direct-posenet#9]
Hi, nerf pytorch is really slow for training, and have you tried ngp on seven scenes? 
Just wondering how would you adapt the poses? And did you get better results? Thanks.

**Comment by chenusc11** [comment]
Hi, yes instance-ngp works as well. And it's faster. I think the key insight of this paper is the proposed framework works with differentiable rendering.

**Comment by cazhang** [comment]
I tried torch-ngp on 7scenes, it looks faster but got very blurry results. And i noticed that ngp is using different camera coordinate as Nerf. Would you like to share your idea on how to modify poses accordingly? 

Many thanks:)

**Comment by chenusc11** [comment]
Hi, honestly, I have no idea cuz I didn't use the original torch-ngp code. 

Maybe you could modify the PyTorch nerf with the reference code from torch-ngp or just ask the author?

Our coordinate system is the same as what original NeRF paper used.

**Comment by cazhang** [comment]
Hi, thanks for the reply. I will try that later. 

I'm closing the issue. Thanks.
